version: '3.9'

services:
  ssh-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ubuntu_ssh_server
    privileged: true
    ports:
      - "2222:22"
      - "8080:8080"
      - "5000:5000"
    restart: unless-stopped 